### ISSUE TITLE
请求移交AppVeyor的管理权

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#62]

**Comment by Miigon** [comment]
@abc612008

**Comment by ascchrvalstr** [comment]
`appveyor.yml`文件内容应为

``` YAML
version: '{build}'
branches:
  only:
  - renew
clone_folder: C:\NEWorld
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/Infinideastudio/NEWorld-binaries/master/dependencies.exe','C:\NEWorld\dependencies.exe')

    C:\NEWorld\dependencies.exe > C:\NEWorld\temp.txt
build:
  project: build/VisualStudio_v14/NEWorld.sln
  verbosity: minimal
```
